version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - wp_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: Pruebas123
       MYSQL_DATABASE: wp_optimazing
       MYSQL_USER: dbOptimazing
       MYSQL_PASSWORD: Pruebas123

   wordpress:
     depends_on:
       - db
     build:
       context: .
       args:
        - WORDPRESS_VERSION=4.9.8
     image: wordpress-optimazing-custom
     volumes:
       - wp_data:/var/www/html/
       - ../optimazing-theme:/var/www/html/wp-content/themes/optimazing
     ports:
       - "80:8080"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wp_optimazing
       WORDPRESS_DB_USER: dbOptimazing
       WORDPRESS_DB_PASSWORD: Pruebas123
       WORDPRESS_URL: http://localhost
       WORDPRESS_TITLE: Optimazing
       WORDPRESS_ADMIN_USER: optimazing
       WORDPRESS_ADMIN_PASS: Pruebas123
       WORDPRESS_ADMIN_EMAIL: pruebas@example.com
volumes:
    wp_db_data:
    wp_data: